# Generated by Django 5.2.9 on 2025-12-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('serial_no', models.IntegerField(default=0)),
                ('book_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('year', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.members')),
            ],
        ),
    ]
