# Generated by Django 5.2.9 on 2025-12-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_committeemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
